-- 02_raw_tables.sql
-- RAW landing table (loaded via Snowflake UI Upload)

USE DATABASE RETAIL_PIPELINE_DB;
USE SCHEMA RAW;

CREATE OR REPLACE TABLE SUPERSTORE_RAW (
  ROW_ID NUMBER,
  ORDER_ID STRING,
  ORDER_DATE STRING,
  SHIP_DATE STRING,
  SHIP_MODE STRING,
  CUSTOMER_ID STRING,
  CUSTOMER_NAME STRING,
  SEGMENT STRING,
  COUNTRY STRING,
  CITY STRING,
  STATE STRING,
  POSTAL_CODE STRING,
  REGION STRING,
  PRODUCT_ID STRING,
  CATEGORY STRING,
  SUB_CATEGORY STRING,
  PRODUCT_NAME STRING,
  SALES NUMBER(12,2),
  QUANTITY NUMBER,
  DISCOUNT NUMBER(6,4),
  PROFIT NUMBER(12,2)
);

-- Note: Load data using Snowsight → Home → Upload local files → load into RAW.SUPERSTORE_RAW