-- 04_gold_kpis.sql
-- GOLD KPI table built from Spark-curated (Databricks output)

USE DATABASE RETAIL_PIPELINE_DB;

CREATE SCHEMA IF NOT EXISTS GOLD;

CREATE OR REPLACE TABLE GOLD.MONTHLY_SALES_PROFIT_SPARK AS
SELECT
  DATE_TRUNC('MONTH', TRY_TO_DATE(ORDER_DATE)) AS MONTH,
  ROUND(SUM(SALES), 2)  AS TOTAL_SALES,
  ROUND(SUM(PROFIT), 2) AS TOTAL_PROFIT,
  ROUND(SUM(PROFIT) / NULLIF(SUM(SALES), 0), 4) AS PROFIT_MARGIN
FROM CURATED.SUPERSTORE_CURATED_SPARK_V2
WHERE TRY_TO_DATE(ORDER_DATE) IS NOT NULL
GROUP BY 1
ORDER BY 1;